apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80 ## le port sur lequel les containers écoutent
      targetPort: 80 ## port exposé en interne dans le cluster
      nodePort: 30080 ## Port d'accès (limité 30000-32767 pour nodePort)
